services:
  express:
    container_name: express-saml
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    command: bash -c "cd /app && npm run dev"
  nginx:
    container_name: nginx-kc-saml
    restart: unless-stopped
    image: nginx
    ports:
      - 4000:80
      - 5000:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sp-pub.crt.pem:/etc/ssl/sp-pub.crt.pem
      - ./sp-pvt.key.pem:/etc/ssl/sp-pvt.key.pem
  keycloak:
    container_name: keycloak17
    image: quay.io/keycloak/keycloak:17.0
    ports:
      - 8443:8443
    volumes:
      - ./idp-kc.crt.pem:/opt/keycloak/conf/idp-kc.crt.pem
      - ./idp-kc.key.pem:/opt/keycloak/conf/idp-kc.key.pem
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/idp-kc.crt.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/idp-kc.key.pem
    command: start-dev
